name: Lint and Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '**/*.md'
        continue-on-error: true
  
  yaml-lint:
    name: YAML Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install yamllint
        run: pip install yamllint
      
      - name: Lint YAML files
        run: |
          yamllint **/*.yml **/*.yaml
        continue-on-error: true
  
  python-lint:
    name: Python Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install linting tools
        run: |
          pip install ruff black flake8
      
      - name: Run ruff
        run: |
          ruff check . --exclude venv
        continue-on-error: true
      
      - name: Check black formatting
        run: |
          black --check . --exclude venv
        continue-on-error: true
  
  r-lint:
    name: R Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
      
      - name: Install lintr
        run: |
          install.packages('lintr')
        shell: Rscript {0}
      
      - name: Lint R files
        run: |
          Rscript -e "lintr::lint_dir('.', pattern = '\\\\.R$')"
        continue-on-error: true
